hugo = [
  { range = ">=0.13, <0.16",   tarball = "%s_%s_linux_amd64.tar.gz", bin = "%s_%s_linux_amd64/%s_%s_linux_amd64" },
  { range = "0.16",            tarball = "%s_%s_linux-64bit.tgz", bin = "hugo" },
  { range = ">=0.17, <0.20.3", tarball = "%s_%s_Linux-64bit.tar.gz", bin = "%s_%s_linux_amd64/%s_%s_linux_amd64" },
  { range = "0.20.3",          tarball = "%s_v%s_Linux-64bit.tar.gz",  bin = "hugo" },
  { range = ">0.20.3, <0.43",  tarball = "%s_%s_Linux-64bit.tar.gz",  bin = "hugo" },
  { range = ">=0.43",          tarball = "%s_extended_%s_Linux-64bit.tar.gz",  bin = "hugo" },
]

gutenberg = [
  { range = ">0.0.5, <0.4.3", tarball = "%s-v%s-x86_64-unknown-linux-gnu.tar.gz", bin = "gutenberg" }
]

zola = [
  { range = ">=0.5.0", tarball = "%s-v%s-x86_64-unknown-linux-gnu.tar.gz", bin = "zola" }
]

mdbook = [
  { range = ">=0.2.0", tarball = "%s-v%s-x86_64-unknown-linux-gnu.tar.gz", bin = "mdbook" }
]
